export interface Author {
  id: string;
  name: string;
  commonName: string;
  slug: string;
  birthYear: number;
  deathYear?: number;
  nationality: string;
  portrait?: string;
  tagline: string;
  biographyExcerpt: string;
  era: string[];
  genres: string[];
  notableWorks: string[];
  workCount: number;
  featured: boolean;
}

// Author database - starting with the essential 20 authors
export const authors: Author[] = [
  // VICTORIAN ERA
  {
    id: 'hg-wells',
    name: 'Herbert George Wells',
    commonName: 'H.G. Wells',
    slug: 'h-g-wells',
    birthYear: 1866,
    deathYear: 1946,
    nationality: 'British',
    tagline: 'The Father of Science Fiction',
    biographyExcerpt: 'Often called "the father of science fiction," Wells wrote classics that defined entire sub-genres: alien invasion (The War of the Worlds), time travel (The Time Machine), and mad science (The Island of Doctor Moreau).',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Time Travel', 'Alien Encounters', 'Mad Scientists', 'Dystopian'],
    notableWorks: ['The Time Machine', 'The War of the Worlds', 'The Island of Doctor Moreau', 'The Invisible Man', 'The First Men in the Moon'],
    workCount: 50,
    featured: true,
  },
  {
    id: 'jules-verne',
    name: 'Jules Gabriel Verne',
    commonName: 'Jules Verne',
    slug: 'jules-verne',
    birthYear: 1828,
    deathYear: 1905,
    nationality: 'French',
    tagline: 'The Pioneer of Scientific Romance',
    biographyExcerpt: 'Verne pioneered the genre of science fiction, imagining submarines, space travel, and technological marvels decades before they existed. His works combined meticulous research with boundless imagination.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Space Adventures', 'Lost Worlds', 'Scientific Romance'],
    notableWorks: ['Journey to the Center of the Earth', 'Twenty Thousand Leagues Under the Sea', 'From the Earth to the Moon', 'Around the World in Eighty Days'],
    workCount: 60,
    featured: true,
  },
  {
    id: 'mary-shelley',
    name: 'Mary Wollstonecraft Shelley',
    commonName: 'Mary Shelley',
    slug: 'mary-shelley',
    birthYear: 1797,
    deathYear: 1851,
    nationality: 'British',
    tagline: 'Creator of the First Science Fiction Novel',
    biographyExcerpt: 'At age 18, Shelley wrote Frankenstein, widely considered the first science fiction novel. Her exploration of scientific responsibility and the nature of humanity remains profoundly relevant 200+ years later.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Mad Scientists', 'Philosophical'],
    notableWorks: ['Frankenstein', 'The Last Man'],
    workCount: 10,
    featured: true,
  },
  {
    id: 'robert-louis-stevenson',
    name: 'Robert Louis Stevenson',
    commonName: 'Robert Louis Stevenson',
    slug: 'robert-louis-stevenson',
    birthYear: 1850,
    deathYear: 1894,
    nationality: 'Scottish',
    tagline: 'Master of Dark Scientific Romance',
    biographyExcerpt: 'Best known for Treasure Island, Stevenson also penned one of literature\'s most enduring tales of scientific horror in Dr Jekyll and Mr Hyde, exploring the duality of human nature through a scientific lens.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Mad Scientists', 'Philosophical'],
    notableWorks: ['The Strange Case of Dr Jekyll and Mr Hyde'],
    workCount: 15,
    featured: false,
  },
  {
    id: 'mark-twain',
    name: 'Samuel Langhorne Clemens',
    commonName: 'Mark Twain',
    slug: 'mark-twain',
    birthYear: 1835,
    deathYear: 1910,
    nationality: 'American',
    tagline: 'America\'s Humorist Tackles Time Travel',
    biographyExcerpt: 'While best known for Tom Sawyer and Huckleberry Finn, Twain wrote one of the earliest and most entertaining time travel novels, A Connecticut Yankee in King Arthur\'s Court, blending satire with scientific speculation.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Time Travel'],
    notableWorks: ['A Connecticut Yankee in King Arthur\'s Court'],
    workCount: 30,
    featured: false,
  },

  // PULP ERA
  {
    id: 'edgar-rice-burroughs',
    name: 'Edgar Rice Burroughs',
    commonName: 'Edgar Rice Burroughs',
    slug: 'edgar-rice-burroughs',
    birthYear: 1875,
    deathYear: 1950,
    nationality: 'American',
    tagline: 'Creator of Tarzan and John Carter',
    biographyExcerpt: 'Burroughs created the planetary romance genre with his Mars series and became one of the most influential pulp writers. His stories of John Carter on Mars and adventures in Pellucidar influenced everything from Star Wars to Avatar.',
    era: ['Pulp Era (1920s-1930s)'],
    genres: ['Space Adventures', 'Lost Worlds', 'Planetary Romance'],
    notableWorks: ['A Princess of Mars', 'The Gods of Mars', 'The Warlord of Mars', 'At the Earth\'s Core'],
    workCount: 70,
    featured: true,
  },
  {
    id: 'ee-doc-smith',
    name: 'Edward Elmer Smith',
    commonName: 'E.E. "Doc" Smith',
    slug: 'e-e-doc-smith',
    birthYear: 1890,
    deathYear: 1965,
    nationality: 'American',
    tagline: 'The Father of Space Opera',
    biographyExcerpt: 'Doc Smith invented space opera with his Skylark and Lensman series. He was the first to imagine faster-than-light travel, galactic civilizations, and epic space battles on a cosmic scale.',
    era: ['Pulp Era (1920s-1930s)'],
    genres: ['Space Opera', 'Space Adventures'],
    notableWorks: ['The Skylark of Space', 'Skylark Three', 'Triplanetary', 'First Lensman'],
    workCount: 20,
    featured: true,
  },
  {
    id: 'a-merritt',
    name: 'Abraham Merritt',
    commonName: 'A. Merritt',
    slug: 'a-merritt',
    birthYear: 1884,
    deathYear: 1943,
    nationality: 'American',
    tagline: 'Master of Weird Fantasy',
    biographyExcerpt: 'Merritt\'s lush, dreamlike prose and imaginative lost world stories made him one of the most popular fantasy writers of the pulp era. His blend of science fiction and weird fantasy influenced countless writers.',
    era: ['Pulp Era (1920s-1930s)'],
    genres: ['Lost Worlds', 'Weird Fantasy'],
    notableWorks: ['The Moon Pool', 'The Metal Monster', 'The Ship of Ishtar'],
    workCount: 15,
    featured: false,
  },

  // GOLDEN AGE
  {
    id: 'isaac-asimov',
    name: 'Isaac Asimov',
    commonName: 'Isaac Asimov',
    slug: 'isaac-asimov',
    birthYear: 1920,
    deathYear: 1992,
    nationality: 'American (Russian-born)',
    tagline: 'The Grand Master of Science Fiction',
    biographyExcerpt: 'One of the "Big Three" of science fiction, Asimov wrote over 500 books. He created the Foundation series, established the Three Laws of Robotics, and made hard science fiction accessible to millions.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Hard Science Fiction', 'Space Opera', 'Robots'],
    notableWorks: ['Foundation', 'I, Robot', 'The Gods Themselves', 'Foundation and Empire'],
    workCount: 500,
    featured: true,
  },
  {
    id: 'robert-heinlein',
    name: 'Robert Anson Heinlein',
    commonName: 'Robert A. Heinlein',
    slug: 'robert-a-heinlein',
    birthYear: 1907,
    deathYear: 1988,
    nationality: 'American',
    tagline: 'Dean of Science Fiction Writers',
    biographyExcerpt: 'One of the most influential and controversial science fiction writers, Heinlein challenged social norms and explored political philosophy through compelling stories. His works range from juvenile adventures to complex adult novels.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Hard Science Fiction', 'Military SF', 'Libertarian'],
    notableWorks: ['Stranger in a Strange Land', 'The Moon is a Harsh Mistress', 'Starship Troopers', 'Double Star'],
    workCount: 60,
    featured: true,
  },
  {
    id: 'arthur-c-clarke',
    name: 'Arthur Charles Clarke',
    commonName: 'Arthur C. Clarke',
    slug: 'arthur-c-clarke',
    birthYear: 1917,
    deathYear: 2008,
    nationality: 'British',
    tagline: 'Prophet of the Space Age',
    biographyExcerpt: 'The third member of the "Big Three," Clarke combined scientific accuracy with philosophical depth. He predicted communication satellites and collaborated with Stanley Kubrick on 2001: A Space Odyssey.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Hard Science Fiction', 'First Contact', 'Space Exploration'],
    notableWorks: ['2001: A Space Odyssey', 'Rendezvous with Rama', 'Childhood\'s End', 'The City and the Stars'],
    workCount: 100,
    featured: true,
  },
  {
    id: 'ray-bradbury',
    name: 'Ray Douglas Bradbury',
    commonName: 'Ray Bradbury',
    slug: 'ray-bradbury',
    birthYear: 1920,
    deathYear: 2012,
    nationality: 'American',
    tagline: 'The Poet of Science Fiction',
    biographyExcerpt: 'Bradbury brought literary quality to science fiction with his poetic prose and humanistic themes. The Martian Chronicles and Fahrenheit 451 are American classics that transcend genre boundaries.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Dystopian', 'Literary SF', 'Mars Stories'],
    notableWorks: ['Fahrenheit 451', 'The Martian Chronicles', 'The Illustrated Man', 'Dandelion Wine'],
    workCount: 50,
    featured: true,
  },
  {
    id: 'alfred-bester',
    name: 'Alfred Bester',
    commonName: 'Alfred Bester',
    slug: 'alfred-bester',
    birthYear: 1913,
    deathYear: 1987,
    nationality: 'American',
    tagline: 'The Stylist of Science Fiction',
    biographyExcerpt: 'Bester revolutionized science fiction with his innovative prose style and complex narratives. The Demolished Man and The Stars My Destination are masterpieces of psychological and literary science fiction.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Psychological SF', 'Literary SF'],
    notableWorks: ['The Demolished Man', 'The Stars My Destination'],
    workCount: 15,
    featured: false,
  },
  {
    id: 'theodore-sturgeon',
    name: 'Theodore Sturgeon',
    commonName: 'Theodore Sturgeon',
    slug: 'theodore-sturgeon',
    birthYear: 1918,
    deathYear: 1985,
    nationality: 'American',
    tagline: 'Humanist of the Golden Age',
    biographyExcerpt: 'Sturgeon brought emotional depth and literary quality to science fiction. His emphasis on human relationships and sexuality was groundbreaking. "90% of everything is crud" - Sturgeon\'s Law.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Literary SF', 'Humanist SF'],
    notableWorks: ['More Than Human', 'Venus Plus X', 'The Dreaming Jewels'],
    workCount: 20,
    featured: false,
  },
  {
    id: 'frederik-pohl',
    name: 'Frederik Pohl',
    commonName: 'Frederik Pohl',
    slug: 'frederik-pohl',
    birthYear: 1919,
    deathYear: 2013,
    nationality: 'American',
    tagline: 'The Satirist of Consumer Culture',
    biographyExcerpt: 'Pohl was a master of satirical science fiction, skewering advertising, consumerism, and corporate culture. As both writer and editor, he shaped the golden age and beyond.',
    era: ['Golden Age (1940s-1950s)'],
    genres: ['Satirical SF', 'Social Commentary'],
    notableWorks: ['The Space Merchants', 'Gateway', 'Man Plus'],
    workCount: 70,
    featured: false,
  },

  // NEW WAVE
  {
    id: 'philip-k-dick',
    name: 'Philip Kindred Dick',
    commonName: 'Philip K. Dick',
    slug: 'philip-k-dick',
    birthYear: 1928,
    deathYear: 1982,
    nationality: 'American',
    tagline: 'Master of Paranoid Realities',
    biographyExcerpt: 'Dick explored the nature of reality, consciousness, and identity in mind-bending novels that influenced countless films. His paranoid, metaphysical stories asked: what is real? His works inspired Blade Runner, Total Recall, and Minority Report.',
    era: ['New Wave (1960s-1970s)'],
    genres: ['Philosophical SF', 'Paranoid Fiction', 'Cyberpunk Precursor'],
    notableWorks: ['Do Androids Dream of Electric Sheep?', 'The Man in the High Castle', 'Ubik', 'A Scanner Darkly'],
    workCount: 45,
    featured: true,
  },
  {
    id: 'ursula-k-le-guin',
    name: 'Ursula Kroeber Le Guin',
    commonName: 'Ursula K. Le Guin',
    slug: 'ursula-k-le-guin',
    birthYear: 1929,
    deathYear: 2018,
    nationality: 'American',
    tagline: 'Explorer of Gender and Society',
    biographyExcerpt: 'Le Guin brought anthropological depth and literary quality to science fiction and fantasy. Her Earthsea and Hainish novels explored gender, society, and culture with unmatched sophistication.',
    era: ['New Wave (1960s-1970s)'],
    genres: ['Anthropological SF', 'Literary SF', 'Feminist SF'],
    notableWorks: ['The Left Hand of Darkness', 'The Dispossessed', 'The Earthsea Cycle', 'The Lathe of Heaven'],
    workCount: 40,
    featured: true,
  },
  {
    id: 'harlan-ellison',
    name: 'Harlan Jay Ellison',
    commonName: 'Harlan Ellison',
    slug: 'harlan-ellison',
    birthYear: 1934,
    deathYear: 2018,
    nationality: 'American',
    tagline: 'The Angry Young Man of Sci-Fi',
    biographyExcerpt: 'Ellison brought New Wave experimentation and emotional intensity to science fiction. A controversial figure known for his fierce independence, he wrote some of the genre\'s most memorable short stories.',
    era: ['New Wave (1960s-1970s)'],
    genres: ['New Wave', 'Experimental', 'Dark SF'],
    notableWorks: ['"I Have No Mouth, and I Must Scream"', '"Repent, Harlequin!" Said the Ticktockman', 'A Boy and His Dog'],
    workCount: 50,
    featured: false,
  },
  {
    id: 'jg-ballard',
    name: 'James Graham Ballard',
    commonName: 'J.G. Ballard',
    slug: 'j-g-ballard',
    birthYear: 1930,
    deathYear: 2009,
    nationality: 'British',
    tagline: 'Prophet of Inner Space',
    biographyExcerpt: 'Ballard pioneered "inner space" science fiction, exploring psychological landscapes rather than outer space. His dystopian visions of modernity and technology were prophetic and disturbing.',
    era: ['New Wave (1960s-1970s)'],
    genres: ['New Wave', 'Dystopian', 'Psychological SF'],
    notableWorks: ['Crash', 'The Drowned World', 'High-Rise', 'Empire of the Sun'],
    workCount: 30,
    featured: false,
  },
  {
    id: 'samuel-r-delany',
    name: 'Samuel Ray Delany Jr.',
    commonName: 'Samuel R. Delany',
    slug: 'samuel-r-delany',
    birthYear: 1942,
    nationality: 'American',
    tagline: 'Literary Experimentalist and Theorist',
    biographyExcerpt: 'Delany brought postmodern literary techniques and queer perspectives to science fiction. His complex, multilayered novels pushed the boundaries of what SF could be, both narratively and thematically.',
    era: ['New Wave (1960s-1970s)'],
    genres: ['New Wave', 'Literary SF', 'Queer SF'],
    notableWorks: ['Dhalgren', 'Babel-17', 'The Einstein Intersection', 'Nova'],
    workCount: 25,
    featured: false,
  },

  // ADDITIONAL NOTABLE AUTHORS
  {
    id: 'arthur-conan-doyle',
    name: 'Sir Arthur Ignatius Conan Doyle',
    commonName: 'Arthur Conan Doyle',
    slug: 'arthur-conan-doyle',
    birthYear: 1859,
    deathYear: 1930,
    nationality: 'British',
    tagline: 'Sherlock\'s Creator Explores Lost Worlds',
    biographyExcerpt: 'While best known for Sherlock Holmes, Conan Doyle wrote influential science fiction including The Lost World, which established the "lost dinosaur" genre, and Professor Challenger stories.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Lost Worlds', 'Adventure'],
    notableWorks: ['The Lost World', 'The Poison Belt'],
    workCount: 60,
    featured: false,
  },
  {
    id: 'edwin-a-abbott',
    name: 'Edwin Abbott Abbott',
    commonName: 'Edwin A. Abbott',
    slug: 'edwin-a-abbott',
    birthYear: 1838,
    deathYear: 1926,
    nationality: 'British',
    tagline: 'Mathematical Fabulist',
    biographyExcerpt: 'Abbott wrote Flatland, a mathematical romance about a two-dimensional world that became a classic thought experiment. His exploration of dimensions influenced both science fiction and popular science.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Philosophical', 'Mathematical SF'],
    notableWorks: ['Flatland: A Romance of Many Dimensions'],
    workCount: 5,
    featured: false,
  },
  {
    id: 'edward-bellamy',
    name: 'Edward Bellamy',
    commonName: 'Edward Bellamy',
    slug: 'edward-bellamy',
    birthYear: 1850,
    deathYear: 1898,
    nationality: 'American',
    tagline: 'Utopian Visionary',
    biographyExcerpt: 'Bellamy\'s Looking Backward imagined a socialist utopia in the year 2000. One of the most influential utopian novels, it sparked a political movement and inspired countless other works.',
    era: ['Victorian (1860s-1890s)'],
    genres: ['Utopian', 'Time Travel', 'Social Commentary'],
    notableWorks: ['Looking Backward: 2000-1887'],
    workCount: 10,
    featured: false,
  },
];
